[package]
name = "pidarr-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
closure = "0.3.0"

console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.8", features = ["csr"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
wasm-sockets = "1.0.0"
