services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies #optional
      - ./qbit/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      testing-services_internal:
        ipv4_address: 172.23.0.3

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbit/config:/config
      - ./qbit/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      testing-services_internal:
        ipv4_address: 172.23.0.2
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      testing-services_internal:
        ipv4_address: 172.23.0.4

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=localhost
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - ./radarr/movies:/input
      - ./tdarr/media:/output
      - ./tdarr/transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    networks:
      testing-services_internal:
        ipv4_address: 172.23.0.5
      

networks:
  testing-services_internal:
    name: testing-services_internal
    ipam:
      config:
        - subnet: "172.23.0.0/25"
          gateway: "172.23.0.1"
    driver: bridge

