services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies #optional
      - ./qbit/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
